spring:
  datasource:
    url: jdbc:mariadb://${JDBC_HOST:localhost}:${JDBC_POST:3306}/${JDBC_DATABASE:react_spring_messenger}
    username: ${JDBC_USERNAME:root}
    password: ${JDBC_PASSWORD:1234}
    type: org.springframework.jdbc.datasource.DriverManagerDataSource

debug: true
